trainingslog/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from activities.views import ActivityListJson

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import django.contrib.auth.views
from django.http import HttpResponse
from activities.models import Activity, Sport
import settings
admin.autodiscover()

urlpatterns = patterns('activities.views',
	url(r'^$', 'list_activities'),
	url(r'^activities/$', 'list_activities'),
	url(r'^activities/get/$', ActivityListJson.as_view(), name='activity_list_json'),
	url(r'^activities/get_json/$', 'get_activity'),
	url(r'^activities/(?P<activity_id>\d+)/$', 'detail'),
	url(r'^activities/add/$', 'add_activity'),
	url(r'^activities/delete/$', 'delete_activity'),
	url(r'^calformula/add/$', 'add_calformula'),
	url(r'^calformula/get/$', 'get_calformula'),
	url(r'^calformula/delete/$', 'delete_calformula'),
	url(r'^sports/add/$', 'add_sport'),
	url(r'^sports/delete/$', 'delete_sport'),
	url(r'^sports/get/$', 'get_sport'),
	url(r'^events/add/$', 'add_event'),
	url(r'^events/delete/$', 'delete_event'),
	url(r'^events/get/$', 'get_event'),
	url(r'^events/$', 'list_event'),
	url(r'^events/get/$', 'get_events'),
	url(r'^equipments/add/$', 'add_equipment'),
	url(r'^equipments/delete/$', 'delete_equipment'),
	url(r'^equipments/get/$', 'get_equipment'),
	url(r'^equipments/$', 'list_equipment'),
	url(r'^reports/$', 'reports'),
	url(r'^reports/get/$', 'get_report_data'),
	url(r'^calendar/$', 'calendar'),
	url(r'^calendar/events/$', 'calendar_get_events'),
	url(r'^settings/$', 'settings'),
	url(r'^profile/$', 'user_profile'),
)

urlpatterns += patterns('health.views',
	url(r'^health/$', 'show_weight'),
	url(r'^health/data/$', 'get_data'),
	url(r'^health/desease/add/$', 'add_desease'),
	url(r'^health/desease/get/$', 'get_desease'),
	url(r'^health/weights/add/$', 'add_weight'),
	url(r'^health/weightgoals/add/$', 'add_weightgoal'),
	url(r'^health/pulses/add/$', 'add_pulse'),
)

urlpatterns += patterns('',
url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain"))
)

urlpatterns += patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
	url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': "/activities/"}),
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

activities/models.py
import jsonfield
import hashlib
import os

from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
import django.core.exceptions


class TrackAlreadyExists(Exception):
	pass


class Parameters(models.Model):
	"""A model that represents a dictionary. This model implements most of the dictionary interface,
	allowing it to be used like a python dictionary.

	"""
	# name = models.CharField(max_length=255)
	content_type = models.ForeignKey(ContentType)
	object_id = models.PositiveIntegerField()
	content_object = generic.GenericForeignKey('content_type', 'object_id')

	@staticmethod
	def getDict(name):
		"""Get the Dictionary of the given name.

		"""
		df = Parameters.objects.select_related().get(name=name)

		return df

	def __getitem__(self, key):
		"""Returns the value of the selected key.

		"""
		return self.keyvaluepair_set.get(key=key).value

	def __setitem__(self, key, value):
		"""Sets the value of the given key in the Dictionary.

		"""
		try:
			kvp = self.keyvaluepair_set.get(key=key)

		except KeyValuePair.DoesNotExist:
			KeyValuePair.objects.create(container=self, key=key, value=value)

		else:
			kvp.value = value
			kvp.save()

	def __delitem__(self, key):
		"""Removed the given key from the Dictionary.

		"""
		try:
			kvp = self.keyvaluepair_set.get(key=key)

		except KeyValuePair.DoesNotExist:
			raise KeyError

		else:
			kvp.delete()

	def __len__(self):
		"""Returns the length of this Dictionary.

		"""
		return self.keyvaluepair_set.count()

	def iterkeys(self):
		"""Returns an iterator for the keys of this Dictionary.

		"""
		return iter(kvp.key for kvp in self.keyvaluepair_set.all())

	def itervalues(self):
		"""Returns an iterator for the keys of this Dictionary.

		"""
		return iter(kvp.value for kvp in self.keyvaluepair_set.all())

	__iter__ = iterkeys

	def iteritems(self):
		"""Returns an iterator over the tuples of this Dictionary.

		"""
		return iter((kvp.key, kvp.value) for kvp in self.keyvaluepair_set.all())

	def keys(self):
		"""Returns all keys in this Dictionary as a list.

		"""
		return [kvp.key for kvp in self.keyvaluepair_set.all()]

	def values(self):
		"""Returns all values in this Dictionary as a list.

		"""
		return [kvp.value for kvp in self.keyvaluepair_set.all()]

	def items(self):
		"""Get a list of tuples of key, value for the items in this Dictionary.
		This is modeled after dict.items().

		"""
		return [(kvp.key, kvp.value) for kvp in self.keyvaluepair_set.all()]

	def get(self, key, default=None):
		"""Gets the given key from the Dictionary. If the key does not exist, it
		returns default.

		"""
		try:
			return self[key]

		except KeyError:
			return default

	def has_key(self, key):
		"""Returns true if the Dictionary has the given key, false if not.

		"""
		return self.contains(key)

	def contains(self, key):
		"""Returns true if the Dictionary has the given key, false if not.

		"""
		try:
			self.keyvaluepair_set.get(key=key)
			return True

		except KeyValuePair.DoesNotExist:
			return False

	def clear(self):
		"""Deletes all keys in the Dictionary.

		"""
		self.keyvaluepair_set.all().delete()

	def __unicode__(self):
		"""Returns a unicode representation of the Dictionary.

		"""
		return unicode(self.asPyDict())

	def asPyDict(self):
		"""Get a python dictionary that represents this Dictionary object.
		This object is read-only.

		"""
		fieldDict = dict()

		for kvp in self.keyvaluepair_set.all():
			fieldDict[kvp.key] = kvp.value

		return fieldDict


class KeyValuePair(models.Model):
	"""A Key-Value pair with a pointer to the Dictionary that owns it.

	"""
	container = models.ForeignKey(Parameters, db_index=True)
	key = models.CharField(max_length=240, db_index=True)
	value = jsonfield.JSONField()


def user_params_get_or_create(obj):
	try:
		return Parameters.objects.get(content_type__pk=ContentType.objects.get_for_model(obj).id, object_id=obj.id)
	except django.core.exceptions.ObjectDoesNotExist:
		params = Parameters(content_type=ContentType.objects.get_for_model(obj), object_id=obj.id)
		params.save()
		return params


User.params = property(lambda u: user_params_get_or_create(u))


class CalorieFormula(models.Model):
	#
	# kcal = weight_dist_factor * weight * distance /(kg * km) + weight_time_factor * weight * time /(kg * h)
	name = models.CharField(max_length=200)
	weight_dist_factor = models.FloatField(default=0.0)
	weight_time_factor = models.FloatField(default=0.0)
	public = models.BooleanField(default=False)
	user = models.ForeignKey(User, null=True, blank=True)

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ["name"]


class Equipment(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField(blank=True)
	distance = models.IntegerField(default=0, blank=True, null=False)
	archived = models.BooleanField(default=False)

	user = models.ForeignKey(User, null=True, blank=True)

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ["name"]


class Event(models.Model):
	name = models.CharField(max_length=200)
	user = models.ForeignKey(User, null=True, blank=True)

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ["name"]


class Sport(models.Model):
	name = models.CharField(max_length=200)
	color = models.CharField(max_length=10)
	user = models.ForeignKey(User, null=True, blank=True)
	speed_as_pace = models.BooleanField(default=False)
	calorie_formula = models.ForeignKey(CalorieFormula, null=True, blank=True)

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ["name"]


class Track(models.Model):
	trackfile = models.FileField(upload_to='uploads/tracks/%Y/%m/%d')
	preview_img = models.FileField(upload_to='uploads/previews/%Y/%m/%d', null=True)
	filetype = models.CharField(max_length=10, null=True)  # FIXME: Need database update procedure; set default "tcx"
	file_sha1 = models.CharField(max_length=40, null=True)

	def generate_sha1(self):
		sha = hashlib.sha1()
		self.trackfile.seek(0)
		while True:
			buf = self.trackfile.read(104857600)
			if not buf:
				break
			sha.update(buf)
		sha1 = sha.hexdigest()
		return sha1

	def delete(self, *args, **kwargs):
		files = []
		if self.trackfile:
			files.append(self.trackfile.path)
			files.append(self.trackfile.path + ".gpx")

		if self.preview_img:
			files.append(self.preview_img.path)

		for f in files:
			if os.path.exists(f):
				try:
					os.remove(f)
				except OSError:
					pass

		models.Model.delete(self, *args, **kwargs)

	def save(self, *args, **kwargs):
		if not self.id:
			self.file_sha1 = self.generate_sha1()

			match_qs = Track.objects.filter(file_sha1=self.file_sha1)
			if match_qs.count() > 0:
				raise TrackAlreadyExists("Track with sha1 %s checksum already exists: %s" % (self.file_sha1, self.trackfile.name))

		models.Model.save(self, *args, **kwargs)


class ActivityBaseClass(models.Model):
	name = models.CharField(max_length=200)
	comment = models.TextField(blank=True)
	sport = models.ForeignKey(Sport, blank=True, null=True)
	equipment = models.ManyToManyField(Equipment, blank=True)
	user = models.ForeignKey(User, null=True, blank=True)
	track = models.ForeignKey(Track, null=True, blank=True)

	cadence_avg = models.IntegerField(blank=True, null=True)
	cadence_max = models.IntegerField(blank=True, null=True)
	calories = models.IntegerField(blank=True, null=True)
	calorie_formula = models.ForeignKey(CalorieFormula, null=True, blank=True)
	distance = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)
	elevation_gain = models.IntegerField(blank=True, null=True)
	elevation_loss = models.IntegerField(blank=True, null=True)
	elevation_min = models.IntegerField(blank=True, null=True)
	elevation_max = models.IntegerField(blank=True, null=True)
	hf_max = models.IntegerField('hf_max', blank=True, null=True)
	hf_avg = models.IntegerField('hf_avg', blank=True, null=True)
	public = models.BooleanField(default=False)
	speed_max = models.DecimalField(max_digits=4, decimal_places=1, blank=True, null=True)
	speed_avg = models.DecimalField(max_digits=4, decimal_places=1, blank=True, null=True)
	speed_avg_movement = models.DecimalField(max_digits=4, decimal_places=1, blank=True, null=True)
	time_elapsed = models.IntegerField(blank=True, null=True)
	time_movement = models.IntegerField(blank=True, null=True)

	weather_stationname = models.CharField(max_length=200, blank=True, null=True)
	weather_temp = models.DecimalField(max_digits=3, decimal_places=1, blank=True, null=True)
	weather_rain = models.DecimalField(max_digits=3, decimal_places=1, blank=True, null=True)
	weather_hum = models.IntegerField(blank=True, null=True)
	weather_windspeed = models.DecimalField(max_digits=4, decimal_places=1, blank=True, null=True)
	weather_winddir = models.CharField(max_length=20, blank=True, null=True)

	def __unicode__(self):
		return self.name

	class Meta:
		def __init__(self):
			pass

		abstract = True


class Activity(ActivityBaseClass):
	date = models.DateTimeField('date')
	event = models.ForeignKey(Event)
	time = models.IntegerField()

	class Meta:
		def __init__(self):
			pass

		verbose_name_plural = "Activities"

	def delete(self, *args, **kwargs):
		if self.track:
			self.track.delete()

		ActivityBaseClass.delete(self, *args, **kwargs)


class ActivityTemplate(ActivityBaseClass):
	date = models.DateTimeField('date', blank=True, null=True)
	event = models.ForeignKey(Event, blank=True, null=True)
	time = models.IntegerField(blank=True, null=True)

	class Meta:
		def __init__(self):
			pass

		verbose_name_plural = "ActivityTemplates"


class Lap(models.Model):
	activity = models.ForeignKey(Activity)
	date = models.DateTimeField('date')
	time = models.IntegerField()
	distance = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
	speed_max = models.DecimalField(max_digits=4, decimal_places=1, blank=True, null=True)

activities/forms.py
# encoding: utf-8
from django import forms
from django.conf import settings as django_settings
from activities.models import Activity, Equipment, Event
import libs.crypto.cipher
import django.core.exceptions


class UserProfileForm(forms.Form):
	PARAMS = [
		('sync_imap_enable', forms.BooleanField(required=False), False),
		('sync_imap_host', forms.CharField(required=False), None),
		('sync_imap_user', forms.CharField(required=False), None),
		('sync_imap_password', forms.CharField(required=False, widget=forms.PasswordInput), None),
		('sync_imap_mailbox', forms.CharField(required=False), None),
		('sync_garminconnect_enable', forms.BooleanField(required=False), False),
		('sync_garminconnect_username', forms.CharField(required=False), None),
		('sync_garminconnect_password', forms.CharField(required=False, widget=forms.PasswordInput), None),
		('frontend_garminplugin_enable', forms.BooleanField(required=False), True)
	]

	def __init__(self, user, *args, **kw):
		self.user = user
		self.cipher = libs.crypto.cipher.AESCipher(django_settings.ENCRYPTION_KEY)

		super(UserProfileForm, self).__init__(*args, **kw)

		for (param, formtype, required) in self.PARAMS:
			self.fields[param] = formtype
			if param in self.user.params:
				# if param in ['sync.imap.enable', 'sync.garminconnect.enable']:
				# 	value = self.user.params[param] == 'True'
				if param in ['sync_imap_password', 'sync_garminconnect_password']:
					value = ''
				else:
					value = self.user.params[param]
				self.fields[param].initial = value

	def save(self, *args, **kw):
		for param in self.changed_data:
			value = self.cleaned_data.get(param)
			if value is not None:
				if param in ['sync_imap_password', 'sync_garminconnect_password']:
					self.user.params[param] = self.cipher.encrypt(value)
				else:
					self.user.params[param] = value

	def clean(self):
		cleaned_data = super(UserProfileForm, self).clean()

		for field in ['sync_imap_password', 'sync_garminconnect_password']:
			if len(self.cleaned_data[field]) == 0:
				try:
					self.cleaned_data[field] = self.user.params[field]
				except django.core.exceptions.ObjectDoesNotExist:
					pass

		for field in ['sync_imap_enable', 'sync_garminconnect_enable']:
			if cleaned_data[field] is not True:
				cleaned_data[field] = False
		return cleaned_data


class ActivityForm(forms.ModelForm):
	class Meta:
		def __init__(self):
			pass

		model = Activity
		fields = ('name', 'comment', 'date', 'event', 'sport', 'equipment', 'cadence_avg', 'cadence_max',
				'calories', 'distance', 'elevation_gain', 'elevation_loss', 'elevation_min', 'elevation_max',
				'hf_max', 'hf_avg', 'speed_max', 'speed_avg', 'speed_avg_movement',
				'time', 'time_elapsed', 'time_movement')


class EquipmentForm(forms.ModelForm):
	class Meta:
		def __init__(self):
			pass

		model = Equipment
		fields = ('name', 'description')


class EventForm(forms.ModelForm):
	class Meta:
		def __init__(self):
			pass

		model = Event
		fields = ('name', )

templates/activities/equipment_form.html
{% if object %}
<h1>Update equipment:</h1>
{% else %}
<h1>Create a equipment</h1>
{% endif %}

{% if form.has_errors %}
<h2>Please correct the following error{{ form.errors|pluralize }}:</h2>
{% endif %}

<form method="post" action=".">
	{{ form.as_p }}
	<input type="submit" value="Submit" />
</form>

<p> {{ form.error_dict }} </p>

templates/activities/equipment_list.html
{% if equipment_list %}
	<table border=1>
		<tr><th>Name</th></tr>
		{% for equ in equipment_list %}
			<tr>
				<td>{{equ.name}}</td>
			</tr>
		{%endfor %}
	</table>
{% else %}
	<p>No equipments are available</p>
{%endif%}

templates/activities/event_form.html
{% if object %}
<h1>Update event:</h1>
{% else %}
<h1>Create a event</h1>
{% endif %}

{% if form.has_errors %}
<h2>Please correct the following error{{ form.errors|pluralize }}:</h2>
{% endif %}

<form method="post" action=".">
	{{ form.as_p }}
	<input type="submit" value="Submit" />
</form>

<p> {{ form.error_dict }} </p>

templates/activities/event_list.html
{% if event_list %}
	<table border=1>
		<tr><th>Name</th></tr>
		{% for event in event_list %}
			<tr>
				<td>{{event.name}}</td>
			</tr>
		{%endfor %}
	</table>
{% else %}
	<p>No events are available</p>
{%endif%}

templates/activities/import.html
{% if tracks %}
    <ul>
    {% for track in tracks %}
        <li><a href="{{ track.trackfile.url }}">{{ track.trackfile.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No tracks.</p>
{% endif %}

templates/activities/settings.html
{% extends "base.html" %}
{% load materializecss %}

{% block title %}Settings{% endblock %}
{% block head %} 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.7/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/media/addons/materialize-colorpicker/js/materialize-colorpicker.js"></script>

<link rel="stylesheet" type="text/css" href="/media/addons/materialize-colorpicker/css/materialize-colorpicker.css" />

<script>
	var equ_id = null;
	var ev_id = null;
	var sp_id = null;
	var cf_id = null;

	var openModal = function(modelName, id){
		if(id != null){
			$("#settings_form_modal_content").load('/forms/'+modelName+'/' + id + '/');
		} else {
			$("#settings_form_modal_content").load('/forms/'+modelName);
		}
		$('#id_color').colorpicker();
		$('#settings_form_modal').openModal({
			ready: function() {
				$('#id_color').colorpicker();
			}
		});
	};

	$(document).ready(function(){
		$('.modal-trigger').click(function() {
			var modelName = this.id.split('.')[3];
			openModal(modelName, null);
		});

		$( ".datatable").dataTable({
 			"bJQueryUI": true,
			"bFilter": false,
			"bInfo": false,
			"bPaginate": false,
			"oLanguage": {
				"sUrl":   "/media/lang/dataTables.de_DE.txt"
			}
		});
		$( ".datatable_equipment").dataTable({
			"aoColumnDefs": [
				{
					"mRender": function ( data, type, full ) {
						if(type=="display"){
							return secondsToTime(data, true, true);
						} else {
							return data;
						}
					},
					"aTargets": [2]
				},
				{
					"mRender": function ( data, type, full ) {
						if(type=="display"){
							if (data != ""){
								return parseFloat(data).toFixed(2).replace( /\./,"," ) + " km/h";
							} else {
								return "-";
							}
						} else {
							return data;
						}
					},
					"aTargets": [3]
				},
				{
					"mRender": function ( data, type, full ) {
						if(type=="display"){
							if (data != ""){
								return parseFloat(data).toFixed(2).replace( /\./,"," ) + " km";
							} else {
								return "-";
							}
						} else {
							return data;
						}
					},
					"aTargets": [1]
				}
			],
 			"bJQueryUI": true,
			"bFilter": false,
			"bInfo": false,
			"bPaginate": false,
			"oLanguage": {
				"sUrl":   "/media/lang/dataTables.de_DE.txt"
			}
		});
	});

	var get_data = function(url, onDataReceived) {
		$.ajax({
		// have to use synchronous here, else the function
		// will return before the data is fetched
		async:false,
		url: url,
		dataType:"json",
		success: onDataReceived
		});
	};
</script>
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col s12">
			<ul class="tabs">
				<li class="tab col s3"><a class="active" href="#tabs-equipment">Equipment</a></li>
				<li class="tab col s3"><a href="#tabs-events">Events</a></li>
				<li class="tab col s3"><a href="#tabs-templates">Vorlagen</a></li>
				<li class="tab col s3"><a href="#tabs-sports">Sportarten</a></li>
				<li class="tab col s3"><a href="#tabs-calformula">Kalorienformeln</a></li>
			</ul>
		</div>

		<div id="tabs-equipment" class="col s12 material-table">
			{% if equipments %}
				<table id="equipment_table" class="datatable_equipment ui compact selectable striped celled table raised segment">
					<thead>
					<tr><th>Name</th><th>Distanz</th><th>Zeit</th><th>Geschwindigkeit</th><th></th></tr>
					</thead>
					<tbody>
					{% for equ in equipments %}
						<tr>
							<td>
								{{equ.name}}&nbsp;&nbsp;
							</td>
							<td>{{equ.distance}}</td>
							<td>{{equ.time}}</td>
							<td>{{equ.speed}}</td>
							<td>
								<i class="material-icons" onclick="openModal('equipment', {{equ.id}})">mode_edit</i>
							</td>
						</tr>
					{%endfor %}
					</tbody>
				</table>
			{% else %}
				<p>No equipments are available</p>
			{%endif%}
			<a id="modal.trainingslog.settings.equipment.add" class="waves-effect waves-light btn modal-trigger"><i class="material-icons left">add</i></a>

			{% if equipments_archived %}
				<h2>Archiv</h2>
				<table id="equipment_archived_table" class="datatable_equipment ui compact selectable striped celled table raised segment">
					<thead>
					<tr><th>Name</th><th>Distanz</th><th>Zeit</th><th>Geschwindigkeit</th><th></th></tr>
					</thead>
					<tbody>
					{% for equ in equipments_archived %}
						<tr>
							<td>
								{{equ.name}}&nbsp;&nbsp;
							</td>
							<td>{{equ.distance}}</td>
							<td>{{equ.time}}</td>
							<td>{{equ.speed}}</td>
							<td>
								<i class="material-icons" onclick="openModal('equipment', {{equ.id}})">mode_edit</i>
							</td>
						</tr>
					{%endfor %}
					</tbody>
				</table>
			{%endif%}
		</div>

		<div id="tabs-events" class="col s12 material-table">
			{% if events %}
				<table id="event_table" class="datatable ui compact selectable striped celled table raised segment">
					<thead>
					<tr>
						<th>Name</th><th></th>
					</tr>
					</thead>
					<tbody>
					{% for event in events %}
						<tr>
							<td>
								{{event.name}}
							</td>
							<td>
								<i class="material-icons" onclick="openModal('event', {{event.id}})">mode_edit</i>
							</td>
						</tr>
					{%endfor %}
					</tbody>

				</table>
			{% else %}
				<p>No events are available</p>
			{%endif%}
			<a id="modal.trainingslog.settings.event.add" class="waves-effect waves-light btn modal-trigger"><i class="material-icons left">add</i></a>
		</div>

		<div id="tabs-templates" class="col s12 material-table">
			{% if activitytemplates %}
				<table id="activitytemplates_table" class="datatable ui compact selectable striped celled table raised segment">
					<thead>
					<tr>
						<th>Name</th><th></th>
					</tr>
					</thead>
					<tbody>
					{% for acttmp in activitytemplates %}
						<tr>
							<td>
								{{acttmp.name}}
							</td>
							<td>
								<i class="material-icons" onclick="showActivityTemplateDialog({{acttmp.id}}, onlytemplate = true)">mode_edit</i>
							</td>
						</tr>
					{%endfor %}
					</tbody>

				</table>
			{% else %}
				<p>Keine Vorlagen vorhanden</p>
			{%endif%}
			<input type="submit" id="acttmp_add" value="Neue Vorlage...">
		</div>

		<div id="tabs-sports" class="col s12 material-table">
			{% if sports %}
				<table id="sport_table" class="datatable ui compact selectable striped celled table raised segment">
					<thead>
					<tr>
						<th>Name</th>
						<th>Kalorienberechnung</th>
						<th>Farbe</th>
						<th></th>
					</tr>
					</thead>
					<tbody>
					{% for sport in sports %}
						<tr>
							<td>
								{{sport.name}}
							</td>
							<td>
								{% if sport.calorie_formula %}
									{{sport.calorie_formula}}
								{% else %}
									-
								{% endif %}
							</td>
							<td>
								<div class="colordisplay">
									<div style="background-color: {{sport.color}}"></div>
								</div>
							</td>
							<td>
								<i class="material-icons" onclick="openModal('sport', {{sport.id}})">mode_edit</i>
							</td>
						</tr>
					{%endfor %}

					</tbody>
				</table>
			{% else %}
				<p>Keine Sportarten festgelegt</p>
			{% endif %}
			<a id="modal.trainingslog.settings.sport.add" class="waves-effect waves-light btn modal-trigger"><i class="material-icons left">add</i></a>
		</div>

		<div id="tabs-calformula" class="col s12 material-table">
			{% if calformulas %}
				<table id="calories_table" class="datatable ui compact selectable striped celled table raised segment">
					<thead>
					<tr>
						<th>Name</th>
						<th>Formel</th>
						<th></th>
					</tr>
					</thead>
					<tbody>
					{% for calformula in calformulas %}
						<tr>
							<td>
								{{calformula.name}}
							</td>
							<td>
								kcal =
								{% if calformula.weight_dist_factor != 0 %}
									Distanz x Gewicht x {{calformula.weight_dist_factor}}
									{% if calformula.weight_time_factor != 0 %} + {% endif %}
								{% endif %}
								{% if calformula.weight_time_factor != 0 %}
									Zeit x Gewicht x {{calformula.weight_time_factor}}
								{% endif %}
							</td>
							<td>
							</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
			{% endif %}
		</div>
	</div>
	<div id="settings_form_modal" class="modal">
		<div id="settings_form_modal_content" class="modal-content">
		</div>
	</div>

{% include "activities/includes/materialize_table_js.html" %}
{% endblock %}

templates/activities/user_profile.html
{% extends "base.html" %}

{% block title %}Benutzerprofil{% endblock %}
{% block head %}
<link rel='stylesheet' type='text/css' href='/media/css/jquery.dataTables_themeroller.css'/>
{% endblock %}
{% block content %}
{% if form.errors %}
	<p style="color: red;">
		Please correct the error{{ form.errors|pluralize }} below.
	</p>
{% endif %}
<form action="" method="post">
		<table id="userprofile_table" class="data_table">
		{{ form }}
	</table>
	{% csrf_token %}
	<input type="submit" value="Submit">
</form>
{% endblock %}